# NOTE:
# Ignored files

# INFO:
# Junk
IgnorePath '/boot/*' # Completely auto-generated junk, should neither change, nor influence much
IgnorePath '/etc/ca-certificates/*'
IgnorePath '/etc/ssl/*'
IgnorePath '/var/lib/*'
IgnorePath '/var/log/*'
IgnorePath '/var/tmp/*'
IgnorePath '/etc/pacman.d/gnupg/*'
IgnorePath '/usr/lib/modules/*'
IgnorePath '/usr/local/bin/*' # should be manageable like $HOME
IgnorePath '/etc/resolv.conf' # managed by dhcpcd
IgnorePath '/etc/fstab' # UUIDs
# IgnorePath '/etc/libvirt' # Junk

# INFO: 
# Password files
IgnorePath '/etc/.pwd.lock'
IgnorePath '/etc/passwd'
IgnorePath '/etc/passwd-'
IgnorePath '/etc/shadow'
IgnorePath '/etc/shadow-'
IgnorePath '/etc/gshadow'
IgnorePath '/etc/gshadow-'
IgnorePath '/etc/group'
IgnorePath '/etc/group-'

# INFO: 
# SSH files
IgnorePath '/etc/ssh'
IgnorePath '/etc/ssh/*'

# INFO:
# Other unnecessary files
IgnorePath '/etc/.updated'
IgnorePath '/var/.updated'
IgnorePath '/etc/adjtime'
IgnorePath '/etc/machine-id'
IgnorePath '/etc/mkinitcpio.d/linux.preset'
IgnorePath '/etc/os-release'
IgnorePath '/lost+found'
IgnorePath '/etc/passwd.OLD'
IgnorePath '/usr/local/man/*'
IgnorePath '/usr/share/terminfo/*'
IgnorePath '/usr/share/mime/*'
IgnorePath '*.cache' # ambitious
IgnorePath '/opt/stm32cubeide/*' # STM32 Cube IDE configuration
IgnorePath '/usr/share/doc/arch-wiki/*' # Arch wiki data
IgnorePath '/opt/brew/*' # Brew config
IgnorePath '/etc/NetworkManager/*'
IgnorePath '/usr/share/icons/Papirus/*'
IgnorePath '/var/db/sudo/lectured/1000'
IgnorePath '/usr/bin/rclone'

# INFO:
# Unknown files
IgnorePath '/usr/lib/locale/locale-archive' # looks to be generated by `locale-gen` from /etc/locale.gen
IgnorePath '/usr/lib/udev/hwdb.bin'
IgnorePath '/usr/share/info/dir'
IgnorePath '/usr/bin/newgidmap' # these two have weird mode changes for some reason
IgnorePath '/usr/bin/newuidmap' #
IgnorePath '/usr/share/glib-2.0/*' #
IgnorePath '/etc/pacman.d/mirrorlist.pacnew'
IgnorePath '/etc/*.pacnew'
IgnorePath  '/etc/shells'
IgnorePath '/etc/brlapi.key'
